Develop
foximilUno/metrics pull request #1
Opened 2022-02-18 21:29 UTC by foximilUno

2022-02-21 22:13 UTC, foximilUno commented
Объяснение почему тесты валятся - позеленить их не смог

TestIteration2/TestCounterHandlers/without_id
	по тесту 404 должен быть а у меня 400 хотя это правильно и логично - возвращаю еще и ошибку
       в запросе не полный path, по требованиям четко было сказано какой должен быть path и его я возвращаю в ошибке
	path must be pattern like /update/<ТИП_МЕТРИКИ>/<ИМЯ_МЕТРИКИ>/<ЗНАЧЕНИЕ_МЕТРИКИ>
TestIteration2/TestGaugeHandlers/without_id
	тоже самое что и counter
TestSaveMetrics/test_content_type_check (0.00s
	была проверка на contenttype - но прищлось убрать т.к. валились тесты которые раньше проходят

2022-02-22 16:19 UTC, sergeysergeevru commented on cmd/server/main.go
> +	})
не очень понятно зачем оборачивать в `r.Route` можно просто сразу писать r.Post/r.Get  С другой стороны ошибкой не считаю это. Просто сейчас получается лишний код. Так что up to you )

2022-02-22 16:23 UTC, sergeysergeevru commented on internal/collector/metric_collector.go
> +	rand.Seed(time.Now().UnixNano())
math/rand нужно сидить только один раз за всю работу программы. Если ты сидишь каждый раз здесь, то теряешь равномерное распределение псевдослучайной последовательности. Поэтому эту строчку надо куда-то уносить

2022-02-22 16:26 UTC, sergeysergeevru commented on internal/collector/metric_collector.go
> +	mc.increaseCounter("PollCount")
как вариант можно вынести названия полей как константы, хотя сейчас тоже норм смотрится.  Если потом поля придется еще где-то дергать такие-же, то тогда советую вынести, чтобы не копипастить. Но сейчас гуд

2022-02-22 16:29 UTC, sergeysergeevru commented on internal/collector/metric_collector.go
> +	client := http.Client{}
вообще http.client можно инкапсулировать в твой collector и переиспользовать. Допустим ты сможешь настроить твой клиент (например сконфигурировать таймаут) когда стартуешь программу и передать уже конструктору `collector`. Или описать интерфейс под клиент, тогда можно еще и мок тесты делать.

2022-02-22 16:31 UTC, sergeysergeevru commented on internal/collector/metric_collector.go
> +	commonURL := "http://" + mc.host + ":" + mc.port + "/update"
молодец что продумал конфигурацию, но есть предложение по импрувменту. Ты можешь просто сделать одним полем `mc.baseUrl + "/update"` что-то типо того. Так более гибко конфигурировать можно. Вдруг тебе с сервером по TLS придется общаться?)

2022-02-22 16:33 UTC, sergeysergeevru commented on internal/collector/metric_collector.go
> +			log.Fatalf("error while send request: %e", err)
если делаешь log.Fatal, то там под капотом os.Exist(1) и программа завершится. Мне кажется можно просто залогировать достаточно

2022-02-22 16:34 UTC, sergeysergeevru commented on internal/collector/metric_collector.go
> +		if resp.StatusCode != 200 {
вообще круто что есть проверка, можно http.StatusOk заместо 200 написать

2022-02-22 16:41 UTC, sergeysergeevru commented on internal/handlers/metric_handler.go
> +		segments := strings.Split(strings.TrimLeft(r.URL.Path, "/"), "/")
Если ты используешь chi, то можно использовать функции фреймворка, чтобы вытаскивать параметры.  Тогда тебе парсить не придется Path, да и валидацию параметров вроде тожа на chi можно взвалить

2022-02-22 16:43 UTC, sergeysergeevru commented on internal/handlers/metric_handler.go
> +		segments := strings.Split(strings.TrimLeft(r.URL.Path, "/"), "/")
Да я ниже описал, что можно переписать хэндлер, чтобы использовать chi функции, а не парсить самому.

2022-02-22 16:44 UTC, sergeysergeevru commented on internal/handlers/metric_handler.go
> +		w.WriteHeader(200)
я бы предпочел http.StatusOK ,

2022-02-22 16:46 UTC, sergeysergeevru commented on internal/handlers/metric_handler.go
> +		w.WriteHeader(http.StatusOK)
WriteHeader тут не применится, если ты уже начал писать респонс выше. В принципе у тебя всегда 200 по дефолту, можно вообще убрать строчку

2022-02-22 16:47 UTC, sergeysergeevru commented on internal/handlers/metric_handler.go
> +			return
давай что ли залогируем ошибку? А то получается смысла в том что проверяли нет)

2022-02-22 16:48 UTC, sergeysergeevru commented on internal/handlers/metric_handler.go
> +			n, _ := s.GetGaugeMetricAsString(v)
если функция возвращается ошибку, то не стоит ее скипать через _. Давай тогда уж проверим?

2022-02-22 16:49 UTC, sergeysergeevru commented on internal/handlers/metric_handler.go
> +			n, _ := s.GetCounterMetricAsString(v)
в догонку про ошибки) https://gist.github.com/adamveld12/c0d9f0d5f0e1fba1e551#handle-errors

2022-02-22 16:50 UTC, sergeysergeevru commented on internal/handlers/metric_handler_test.go
> +			if err != nil {
на сколько помню можно юзать assert.NoError, вроде так пишется

2022-02-22 16:51 UTC, sergeysergeevru commented on internal/handlers/metric_handler_test.go
> +			req, _ := http.NewRequest(tt.args.method, tt.args.url, nil)
тут тоже можно завалидировать ошибку

2022-02-22 16:53 UTC, sergeysergeevru commented on internal/storage/metric_storage.go
> +		log.Printf("cant increase counter with name %s: %e\r\n", name, err)
я бы в таком случае советовал кинуть ошибку на слой выше и там уже бы решал что делать с ней. Например можешь отдать клинету информацию об ошибке

2022-02-22 17:08 UTC, sergeysergeevru commented on cmd/agent/main.go
> +	}()
Смотри, тут у тебя получается загводка, что на первый сигнал может ничего не произойти если первой отреагирует чтение из канала в горутине. Не нашел этого в задании, если я не прав уточни пожалуйста про это)

2022-02-22 17:16 UTC, sergeysergeevru requested changes
В общем я впечатлен качеством работы: очень хорошая архитектура приложения. Но я вынужден запросить изменения, в первую очередь, хочу чтобы мы закрыли вопрос с тестами. Если я правильно понимаю, то на второй итерации мы запускаем test coverage относительно твоих тестов, очень похоже тесты, которые ты написал как раз и заваливаются. Поэтому валится наш тест за вторую итерацию, так как все твои тесты должны проходить. В основном мои комментарии - пожелания/советы. Из относительно критичного: непонятная горутина в server/main.go (если я что-то не понял, добавь коммент к моему перед тем как на следующее ревью отправишь). И было бы классно поправить некоторые вещи c обработкой ошибок, может прокинуть выше, заместо того чтобы просто логировать в сторадже или вызывать log.Fatal. Жду правок, спасибо! 😉

2022-02-24 20:57 UTC, foximilUno commented on cmd/server/main.go
> +	})
сделано

2022-02-24 20:57 UTC, foximilUno commented on internal/collector/metric_collector.go
> +	rand.Seed(time.Now().UnixNano())
сделано

2022-02-24 20:58 UTC, foximilUno commented on internal/collector/metric_collector.go
> +	mc.increaseCounter("PollCount")
большое количество полей и разные поля разного типа - какое приводить какое нет - пока не понял как. Где то видел мнение что если  enum разрастается в очень большие объекмы то лучше не использовать. пока подумаю

2022-02-24 21:35 UTC, foximilUno commented on internal/collector/metric_collector.go
> +	client := http.Client{}
добавил возможность использовать дефолтный или добавить свой

2022-02-24 21:39 UTC, foximilUno commented on internal/collector/metric_collector.go
> +	commonURL := "http://" + mc.host + ":" + mc.port + "/update"
готово

2022-02-24 21:40 UTC, foximilUno commented on internal/collector/metric_collector.go
> +			log.Fatalf("error while send request: %e", err)
я сделал просто логирование ошибки и у меня тест 1 висит вечно, я так понял ожидается что клиент без сервака упадет

2022-02-24 21:44 UTC, foximilUno commented on internal/collector/metric_collector.go
> +		if resp.StatusCode != 200 {
готово

2022-02-24 22:39 UTC, foximilUno commented on internal/handlers/metric_handler.go
> +		segments := strings.Split(strings.TrimLeft(r.URL.Path, "/"), "/")
готово

2022-02-24 22:43 UTC, foximilUno commented on internal/handlers/metric_handler.go
> +		segments := strings.Split(strings.TrimLeft(r.URL.Path, "/"), "/")
готово

2022-02-24 22:44 UTC, foximilUno commented on internal/handlers/metric_handler.go
> +		w.WriteHeader(200)
сттранно почему go vet не поругался, поправил

2022-02-24 22:45 UTC, foximilUno commented on internal/handlers/metric_handler.go
> +		w.WriteHeader(http.StatusOK)
готово

2022-02-24 22:51 UTC, foximilUno commented on internal/handlers/metric_handler.go
> +			return
готово

2022-02-24 22:54 UTC, foximilUno commented on internal/handlers/metric_handler.go
> +			n, _ := s.GetGaugeMetricAsString(v)
готово

2022-02-24 23:36 UTC, foximilUno commented on internal/handlers/metric_handler.go
> +		segments := strings.Split(strings.TrimLeft(r.URL.Path, "/"), "/")
с этим я конечно споткнулся - мои тесты перестали работать 
 chi.URLParam(r, "<mapped value>") - работает с контекстом - если в тестах через recorder запускать функцию  в моем исполнении то значения из path маппятся в пустую строку

2022-02-28 16:56 UTC, foximilUno commented
поправил все замечания, начинаю второй спринт, извините за задержку

2022-03-01 06:37 UTC, sergeysergeevru commented on internal/collector/metric_collector.go
> +func (mc *collector) WithClient(client *http.Client) *collector {
похоже ты не используешь в настоящее время этот метод, не вижу референсов :)

2022-03-01 06:38 UTC, sergeysergeevru commented on internal/collector/metric_collector.go
> +		&http.Client{},
клиент можно прокидывать вместе с baseUrl в аргументах конструктора. Это удобно, потому что ты можешь настроить его где-то выше (допустим поставить таймаут и тому подобное).

2022-03-01 06:45 UTC, sergeysergeevru approved these changes
Гуд, спасибо за внесенные изменения!) Удачи на втором спринте!

2022-03-02 21:07 UTC, merged